### ISSUE TITLE
creates files with german umlauts

### ISSUE THREAD

**Issue by polarwinkel** [kiney/tiddlywiki_json-to-markdown#1]
it creates files containing german umlauts in the filename if the tiddler has a name containing them.

That leads to the following issue if using the result in Gollum Wiki:

Encoding::CompatibilityError at /edit/Home
incompatible character encodings: UTF-8 and ASCII-8BIT

renaming all .md-files so that the filenames have no special Character like Umlaute "ä" etc. makes the result usable in Gollum Wiki.

**Comment by kiney** [comment]
i made a fix, but didn't test it. I don't have any tiddly wiki data at hand right now.
Can you confirm the fix?

**Comment by polarwinkel** [comment]
confirm, it works.
on Ubuntu just be sure to install the package `python3-unidecode`.
Umlauts like 'ä' are replaced my 'a' instead of 'ae', for me this behaviour is just fine.
